import{a as w,S as $,i as a}from"./assets/vendor-CrlV4O_2.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const B="https://pixabay.com/api/",M="50644019-b9f34b82140387cf531c9f13f";async function h(s,o){const r={key:M,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};return(await w.get(B,{params:r})).data}const g=document.querySelector(".gallery"),y=document.querySelector(".loader"),L=document.querySelector(".load-more");let R=new $(".gallery a");function b(s){const o=s.map(({webformatURL:r,largeImageURL:n,tags:e,likes:t,views:i,comments:S,downloads:q})=>`
        <li class="gallery-item">
          <a href="${n}">
            <img src="${r}" alt="${e}" />
          </a>
          <div class="info">
            <span>👍 ${t}</span>
            <span>👁️ ${i}</span>
            <span>💬 ${S}</span>
            <span>⬇️ ${q}</span>
          </div>
        </li>
      `).join("");g.insertAdjacentHTML("beforeend",o),R.refresh()}function E(){g.innerHTML=""}function v(){y.classList.remove("is-hidden")}function c(){y.classList.add("is-hidden")}function O(){L.classList.remove("is-hidden")}function d(){L.classList.add("is-hidden")}const p=document.querySelector(".form"),m=document.querySelector(".gallery"),P=document.querySelector(".load-more");let u="",l=1,f=0;p.addEventListener("submit",async s=>{s.preventDefault();const o=p.elements["search-text"].value.trim();if(!o){a.error({message:"Введіть слово для пошуку!",position:"topRight"});return}u=o,l=1,E(),d(),v();try{const r=await h(u,l);if(c(),f=r.totalHits,!r.hits.length){a.info({message:"Нічого не знайдено. Спробуйте інший запит!",position:"topRight"});return}b(r.hits),f>15?O():d()}catch{c(),a.error({message:"Сталася помилка. Спробуйте пізніше.",position:"topRight"})}});P.addEventListener("click",async()=>{l+=1,v();try{const s=await h(u,l);c(),b(s.hits);const{height:o}=m.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),m.children.length>=f&&(d(),a.info({message:"Ви дійшли до кінця результатів.",position:"topRight"}))}catch{c(),a.error({message:"Сталася помилка. Спробуйте пізніше.",position:"topRight"})}});
//# sourceMappingURL=index.js.map
